version: '2.1'

services:
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        REQUIREMENTS_FILE: "dev.txt"
    command: bash -c "sleep 10 && /code/scripts/wait-for-it.sh db:5432 && . /code/scripts/runtests.sh"
    environment:
      DATABASE_URL: "postgis://test:test@db/test"
      DJANGO_SETTINGS_MODULE: "config.settings.dev"
      SOCIAL_AUTH_FACEBOOK_KEY: ""
      SOCIAL_AUTH_FACEBOOK_SECRET: ""
