version: 1
task_definition:
  ecs_network_mode: awsvpc
  task_execution_role: ${CONTAINER_TASK_ROLE_ARN}
  task_role_arn: ${CONTAINER_TASK_ROLE_ARN}
  task_size:
    mem_limit: ${SCHEDULER_TASK_MEM_LIMIT}
    cpu_limit: ${SCHEDULER_TASK_CPU_LIMIT}
  services:
    ${SCHEDULER_CONTAINER_NAME}:
      essential: True
      cpu_shares: ${SCHEDULER_CONTAINER_CPU_SHARES}
      mem_limit: ${SCHEDULER_CONTAINER_MEM_LIMIT}
      mem_reservation: ${SCHEDULER_CONTAINER_MEM_RESERVATION}

run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - ${CONTAINER_SUBNET1}
        - ${CONTAINER_SUBNET2}
      security_groups:
        - ${CONTAINER_SG}
      assign_public_ip: ENABLED